### ISSUE TITLE
Fixing load errors on systems where multi-byte characters are present… 

### ISSUE THREAD

**Issue by duveen** [SketchUp/sketchup-stl#154]
I am Korean and are not good at English. Please understand.
This error was fixed #134 from. But, Korean language in the same error occurs.

```
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/importer.rb File road error
Error: #<ArgumentError: invalid byte sequence in CP949>
C:/Program Files/SketchUp/SketchUp 2015/Tools/sketchup.rb:36:in `downcase'
C:/Program Files/SketchUp/SketchUp 2015/Tools/sketchup.rb:36:in `file_loaded?'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/importer.rb:415:in `<top (required)>'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:20:in `require'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:20:in `<module:STL>'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:8:in `<module:CommunityExtensions>'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:7:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2015/Tools/extensions.rb:197:in `require'
C:/Program Files/SketchUp/SketchUp 2015/Tools/extensions.rb:197:in `load'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:58:in `register_extension'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:58:in `<module:STL>'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:12:in `<module:CommunityExtensions>'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:11:in `<top (required)>'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/exporter.rb File road error
Error: #<ArgumentError: invalid byte sequence in CP949>
C:/Program Files/SketchUp/SketchUp 2015/Tools/sketchup.rb:36:in `downcase'
C:/Program Files/SketchUp/SketchUp 2015/Tools/sketchup.rb:36:in `file_loaded?'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/exporter.rb:315:in `<module:Exporter>'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/exporter.rb:11:in `<module:STL>'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/exporter.rb:10:in `<module:CommunityExtensions>'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/exporter.rb:9:in `<top (required)>'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:21:in `require'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:21:in `<module:STL>'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:8:in `<module:CommunityExtensions>'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:7:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2015/Tools/extensions.rb:197:in `require'
C:/Program Files/SketchUp/SketchUp 2015/Tools/extensions.rb:197:in `load'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:58:in `register_extension'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:58:in `<module:STL>'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:12:in `<module:CommunityExtensions>'
C:/Users/박민규/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:11:in `<top (required)>'
```

Up to date, and rb a result of the latest issue been applied to load the file. Fix please

**Comment by thomthom** [comment]
This is with the latest version, 2.1.4?

**Comment by Sam-C** [comment]
same error here. I am using Windows 10 (Chinese), latest SketchUp and latest sketchup-stl plugin. The installation was "successful", but when I restart sketchUp, this error message popped up. The export stl option never shows up in the drop-down menu.
```
Error Loading File C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/importer.rb
Error: #<ArgumentError: invalid byte sequence in CP950>
C:/Program Files/SketchUp/SketchUp 2015/Tools/sketchup.rb:36:in `downcase'
C:/Program Files/SketchUp/SketchUp 2015/Tools/sketchup.rb:36:in `file_loaded?'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/importer.rb:418:in `<top (required)>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:25:in `require'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:25:in `<module:STL>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:13:in `<module:CommunityExtensions>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:12:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2015/Tools/extensions.rb:197:in `require'
C:/Program Files/SketchUp/SketchUp 2015/Tools/extensions.rb:197:in `load'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:60:in `register_extension'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:60:in `<module:STL>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:14:in `<module:CommunityExtensions>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:13:in `<top (required)>'
Error Loading File C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/exporter.rb
Error: #<ArgumentError: invalid byte sequence in CP950>
C:/Program Files/SketchUp/SketchUp 2015/Tools/sketchup.rb:36:in `downcase'
C:/Program Files/SketchUp/SketchUp 2015/Tools/sketchup.rb:36:in `file_loaded?'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/exporter.rb:334:in `<module:Exporter>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/exporter.rb:14:in `<module:STL>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/exporter.rb:13:in `<module:CommunityExtensions>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/exporter.rb:12:in `<top (required)>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:26:in `require'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:26:in `<module:STL>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:13:in `<module:CommunityExtensions>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:12:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2015/Tools/extensions.rb:197:in `require'
C:/Program Files/SketchUp/SketchUp 2015/Tools/extensions.rb:197:in `load'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:60:in `register_extension'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:60:in `<module:STL>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:14:in `<module:CommunityExtensions>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:13:in `<top (required)>'
```

**Comment by jimfoltz** [comment]
Would you try this version to see if it helps?

https://github.com/jimfoltz/sketchup-stl/releases/tag/untagged-cf496cdb45f56177c158

**Comment by jimfoltz** [comment]
@Sam-C @duveen 

Oops, here is the correct link:

https://github.com/jimfoltz/sketchup-stl/releases/tag/v2.1.5-154.1

**Comment by Sam-C** [comment]
Thank you for the lightning fast reply. 

I tried your plugin but it seems the problem persists. The error message is as below:
```
Error Loading File C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/importer.rb
Error: #<ArgumentError: invalid byte sequence in CP950>
C:/Program Files/SketchUp/SketchUp 2015/Tools/sketchup.rb:36:in `downcase'
C:/Program Files/SketchUp/SketchUp 2015/Tools/sketchup.rb:36:in `file_loaded?'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/importer.rb:419:in `<top (required)>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:25:in `require'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:25:in `<module:STL>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:13:in `<module:CommunityExtensions>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:12:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2015/Tools/extensions.rb:197:in `require'
C:/Program Files/SketchUp/SketchUp 2015/Tools/extensions.rb:197:in `load'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:60:in `register_extension'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:60:in `<module:STL>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:14:in `<module:CommunityExtensions>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:13:in `<top (required)>'
Error Loading File C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/exporter.rb
Error: #<ArgumentError: invalid byte sequence in CP950>
C:/Program Files/SketchUp/SketchUp 2015/Tools/sketchup.rb:36:in `downcase'
C:/Program Files/SketchUp/SketchUp 2015/Tools/sketchup.rb:36:in `file_loaded?'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/exporter.rb:334:in `<module:Exporter>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/exporter.rb:14:in `<module:STL>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/exporter.rb:13:in `<module:CommunityExtensions>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/exporter.rb:12:in `<top (required)>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:26:in `require'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:26:in `<module:STL>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:13:in `<module:CommunityExtensions>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl/loader.rb:12:in `<top (required)>'
C:/Program Files/SketchUp/SketchUp 2015/Tools/extensions.rb:197:in `require'
C:/Program Files/SketchUp/SketchUp 2015/Tools/extensions.rb:197:in `load'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:60:in `register_extension'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:60:in `<module:STL>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:14:in `<module:CommunityExtensions>'
C:/Users/守建/AppData/Roaming/SketchUp/SketchUp 2015/SketchUp/Plugins/sketchup-stl.rb:13:in `<top (required)>'
```
(I deleted the old sketchup-stl.rb and the sketchup-stl folder before installing your version.)

**Comment by thomthom** [comment]
Jim, the problem looks to be the string sent to file_loaded?

**Comment by Sam-C** [comment]
ohh, I forgot to mention that I created a new user account called "visitor" and installed the plug-in there. The path was 
```C:\Users\visitor\AppData\Roaming\SketchUp\SketchUp 2015\SketchUp\Plugins\sketchup-stl```
and the it worked fine.

**Comment by duveen** [comment]
In a language other than English, it will not be able to run the STL PLUGIN.

**Comment by thomthom** [comment]
@duveen and @Sam-C - can you download the RBZ from this page (https://github.com/thomthom/sketchup-stl/releases/tag/fix-unicode-username) and test if that solves the load errors?

(If there are still errors - please post them back here.)

**Comment by jimfoltz** [comment]
I am beginning to wonder if there is a purpose to using `file_loaded?` at all?

**Comment by thomthom** [comment]
There is a point to prevent UI and importers/exporters as well as `Sketchup.register_extension` from triggering more than once. But one doesn't have to use `file_loaded` - you can roll your own.

But the issue here is bugs in Ruby itself - where `__FILE__` and `ENV` strings will have the wrong encoding label. I've reported to the Ruby core team, but they've been concerned about fixing it might break existing applications.

**Comment by jimfoltz** [comment]
Under what circumstances would `register_extension` be called more than once? And if it is being called more than once, would not that be a bug (or configuration issue) that should be exposed rather than suppressed?

**Comment by thomthom** [comment]
While developing you often need to reload files. But also other than that you might risk your files being loaded more than once due to differences of how `require`, `load`, `Sketchup.require` and `require_all` works.
There's a number of subtle ways out of your control an RB file could be reloaded - such that a load guard is needed.

**Comment by Sam-C** [comment]
I installed from https://github.com/thomthom/sketchup-stl/releases/tag/fix-unicode-username and it fixed the loading error. :smile:

**Comment by thomthom** [comment]
Thanks for testing. I'll create a pull-request to have that fix included and make a new release.

**Comment by jimfoltz** [comment]
Does SKUI core.rb have a similar issue using `__FILE__`?

**Comment by thomthom** [comment]
Looking over the SKUI code it doesn't look to be the case. It fetches `__FILE__` once, but then makes sure to correct the encoding before passing the string around the system.

**Comment by jimfoltz** [comment]
To be honest, I am not certain using 'self.name' is the best way.  For one, the name of the method is *file*_loaded indicating it is expecting a file. 

In some extensions I have been using 'if defined?(ModuleName::PluginName)' at the top of the file.

**Comment by thomthom** [comment]
It doesn't matter too much - as long as the string you pass is unique for the load guard you are creating. You could use a GUID if you want.
